# Generated by Django 2.1 on 2018-08-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.TextField()),
                ('type', models.TextField()),
                ('subtype', models.TextField()),
                ('alignment', models.TextField()),
                ('armor_class', models.IntegerField()),
                ('hit_points', models.IntegerField()),
                ('hit_dice', models.TextField()),
                ('speed', models.TextField()),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('consitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
                ('constitution_save', models.IntegerField()),
                ('intelligence_save', models.IntegerField()),
                ('wisdom_save', models.IntegerField()),
                ('perception', models.IntegerField()),
                ('damage_vulnerabilities', models.TextField()),
                ('damage_resistances', models.TextField()),
                ('damage_immunities', models.TextField()),
                ('condition_immunities', models.TextField()),
                ('senses', models.TextField()),
                ('languages', models.TextField()),
                ('challenge_rating', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('higher_level', models.TextField()),
                ('page', models.TextField()),
                ('range', models.TextField()),
                ('components', models.TextField()),
                ('material', models.TextField()),
                ('ritual', models.TextField()),
                ('duration', models.TextField()),
                ('concentration', models.TextField()),
                ('casting_time', models.TextField()),
                ('level', models.TextField()),
                ('school', models.TextField()),
                ('dnd_class', models.TextField()),
                ('archetype', models.TextField()),
                ('circles', models.TextField()),
            ],
        ),
    ]
