# Generated by Django 2.1 on 2018-08-25 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archetype',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_proficiencies', models.TextField()),
                ('languages', models.TextField()),
                ('equipment', models.TextField()),
                ('feature', models.TextField()),
                ('suggested_characteristics', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hit_dice', models.TextField()),
                ('hp_at_1st_level', models.TextField()),
                ('hp_at_higher_levels', models.TextField()),
                ('prof_armor', models.TextField()),
                ('prof_weapons', models.TextField()),
                ('prof_tools', models.TextField()),
                ('prof_saving_throws', models.TextField()),
                ('prof_skills', models.TextField()),
                ('equipment', models.TextField()),
                ('table', models.TextField()),
                ('spellcasting_ability', models.TextField()),
                ('subtypes', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('license', models.TextField()),
                ('author', models.TextField()),
                ('organization', models.TextField()),
                ('version', models.TextField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prerequisite', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.TextField()),
                ('type', models.TextField()),
                ('subtype', models.TextField()),
                ('alignment', models.TextField()),
                ('armor_class', models.IntegerField(default=12)),
                ('hit_points', models.IntegerField(null=True)),
                ('hit_dice', models.TextField()),
                ('speed', models.TextField()),
                ('strength', models.IntegerField(null=True)),
                ('dexterity', models.IntegerField(null=True)),
                ('constitution', models.IntegerField(null=True)),
                ('intelligence', models.IntegerField(null=True)),
                ('wisdom', models.IntegerField(null=True)),
                ('charisma', models.IntegerField(null=True)),
                ('constitution_save', models.IntegerField(null=True)),
                ('intelligence_save', models.IntegerField(null=True)),
                ('wisdom_save', models.IntegerField(null=True)),
                ('perception', models.IntegerField(null=True)),
                ('damage_vulnerabilities', models.TextField()),
                ('damage_resistances', models.TextField()),
                ('damage_immunities', models.TextField()),
                ('condition_immunities', models.TextField()),
                ('senses', models.TextField()),
                ('languages', models.TextField()),
                ('challenge_rating', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asi_desc', models.TextField()),
                ('asi', models.TextField()),
                ('age', models.TextField()),
                ('alignment', models.TextField()),
                ('size', models.TextField()),
                ('speed', models.TextField()),
                ('speed_desc', models.TextField()),
                ('languages', models.TextField()),
                ('vision', models.TextField()),
                ('traits', models.TextField()),
                ('subtypes', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('higher_level', models.TextField()),
                ('page', models.TextField()),
                ('range', models.TextField()),
                ('components', models.TextField()),
                ('material', models.TextField()),
                ('ritual', models.TextField()),
                ('duration', models.TextField()),
                ('concentration', models.TextField()),
                ('casting_time', models.TextField()),
                ('level', models.TextField()),
                ('school', models.TextField()),
                ('dnd_class', models.TextField()),
                ('archetype', models.TextField()),
                ('circles', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubRace',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asi_desc', models.TextField()),
                ('asi', models.TextField()),
                ('traits', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
                ('parent_race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='condition',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='charclass',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='background',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='char_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.CharClass'),
        ),
        migrations.AddField(
            model_name='archetype',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document'),
        ),
    ]
