# Generated by Django 2.1 on 2018-08-26 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrace',
            name='parent_race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='api.Race'),
        ),
    ]
