# Generated by Django 2.1 on 2018-08-26 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180826_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='subtypes',
        ),
    ]
