# Generated by Django 2.1 on 2018-08-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_race_subtypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charclass',
            old_name='subtypes',
            new_name='subtypes_name',
        ),
    ]
