# Generated by Django 2.1 on 2018-08-02 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180802_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='charisma',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='constitution',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='constitution_save',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dexterity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='intelligence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='intelligence_save',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='perception',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='wisdom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='wisdom_save',
            field=models.IntegerField(null=True),
        ),
    ]
