# Generated by Django 2.1 on 2018-08-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180802_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameContentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('license', models.TextField()),
                ('author', models.TextField()),
                ('organization', models.TextField()),
                ('version', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
