# Generated by Django 2.1 on 2018-08-28 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180826_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='archetype',
            name='route',
            field=models.TextField(default='archetypes/'),
        ),
        migrations.AddField(
            model_name='background',
            name='route',
            field=models.TextField(default='backgrounds/'),
        ),
        migrations.AddField(
            model_name='charclass',
            name='route',
            field=models.TextField(default='classes/'),
        ),
        migrations.AddField(
            model_name='condition',
            name='route',
            field=models.TextField(default='conditions/'),
        ),
        migrations.AddField(
            model_name='feat',
            name='route',
            field=models.TextField(default='conditions/'),
        ),
        migrations.AddField(
            model_name='monster',
            name='route',
            field=models.TextField(default='monsters/'),
        ),
        migrations.AddField(
            model_name='plane',
            name='route',
            field=models.TextField(default='planes/'),
        ),
        migrations.AddField(
            model_name='race',
            name='route',
            field=models.TextField(default='races/'),
        ),
        migrations.AddField(
            model_name='section',
            name='route',
            field=models.TextField(default='sections/'),
        ),
        migrations.AddField(
            model_name='spell',
            name='route',
            field=models.TextField(default='spells/'),
        ),
        migrations.AddField(
            model_name='subrace',
            name='route',
            field=models.TextField(default='subraces/'),
        ),
        migrations.AlterField(
            model_name='archetype',
            name='char_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archetypes', to='api.CharClass'),
        ),
    ]
