# Generated by Django 2.1 on 2018-09-02 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_monster_speed_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='speed_json',
        ),
    ]
