# Generated by Django 2.1 on 2018-08-24 20:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180824_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('skill_proficiencies', models.TextField()),
                ('languages', models.TextField()),
                ('equipment', models.TextField()),
                ('feature', models.TextField()),
                ('suggested_characteristics', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
