# Generated by Django 2.1 on 2018-09-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_monster_speed_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='actions_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='legendary_actions_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='reactions_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monster',
            name='special_abilities_json',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
