# Generated by Django 2.1 on 2018-09-04 02:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180903_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('slug', models.SlugField(default=uuid.uuid1, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.TextField()),
                ('rarity', models.TextField()),
                ('requires_attunement', models.TextField()),
                ('route', models.TextField(default='magicitems/')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
