# Generated by Django 2.1 on 2018-09-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_magicitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='feature_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
