# Generated by Django 2.1 on 2018-09-21 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_background_feature_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='speed',
            new_name='speed_json',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='asi',
            new_name='asi_json',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='speed',
            new_name='speed_json',
        ),
        migrations.RemoveField(
            model_name='subrace',
            name='asi',
        ),
    ]
