# Generated by Django 2.1 on 2018-09-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_subrace_asi_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='charisma_save',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='dexterity_save',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='strength_save',
            field=models.IntegerField(null=True),
        ),
    ]
