# Generated by Django 2.1 on 2018-09-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180921_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='armor_desc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='group',
            field=models.TextField(null=True),
        ),
    ]
