# Generated by Django 2.1.3 on 2018-11-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180926_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.TextField(null=True),
        ),
    ]
