# Generated by Django 2.1 on 2018-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180926_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='level_int',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
