#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx pretty-quick --staged
npm run lintfix
git add $(git diff --name-only --cached --diff-filter=d)
git commit --amend --no-edit --allow-empty --no-verify
